# Generated by Django 4.1.7 on 2023-02-27 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500, verbose_name='description')),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_end', models.DateTimeField()),
                ('turn_number', models.IntegerField(default=1)),
                ('progress_status', models.CharField(choices=[('En attente', 'PENDING'), ('en cours', 'IN_PROGESS'), ('Annulé', 'CANCELLED'), ('Terminé', 'COMPLETED')], default='En attente', max_length=200)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[("Création d'un vote", 'NEW_VOTE'), ("Rapplel d'un vote en cours", 'RAPPEL'), ("Résultat d'une élection", 'ELLECTION_RESUSLT'), ("Demande de droits d'Admin de vote", 'ADMIN_REQUEST')], max_length=500)),
                ('notif_content', models.TextField(max_length=1000)),
                ('notif_read_status', models.BooleanField(default=False)),
                ('sent_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=500)),
                ('image', models.ImageField(default='static/images/default_option.jpg', upload_to='options_images')),
                ('vote_counter', models.IntegerField(null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='votifyApp.election')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateElection',
            fields=[
                ('election_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='votifyApp.election')),
                ('authorized_voters_file', models.FileField(null=True, upload_to='')),
                ('voters_email', models.JSONField(null=True, verbose_name='Mail des Voters')),
            ],
            bases=('votifyApp.election',),
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_type', models.CharField(choices=[('CANDIDAT', 'CANDIDATE'), ('CITOYEN', 'CITIZEN')], default='CITOYEN', max_length=100)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoteAdminRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500)),
                ('message', models.TextField(max_length=1000)),
                ('creator_identity_piece', models.ImageField(default='static/images/default_piece.jpg', upload_to='identity_pieces')),
                ('is_validated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choosed_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='votifyApp.option')),
                ('election', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='votifyApp.election')),
                ('voter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='votifyApp.voter')),
            ],
        ),
    ]
